### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by deepword18** [anishathalye/dotfiles#11]
I cloned it an ran ./install and I get the following error:
```
% ./install
All targets have been cleaned
Link exists ~/.dotfiles -> /Users/dipamvasani/dotfiles/
Link exists ~/.bash -> /Users/dipamvasani/dotfiles/bash
Link exists ~/.gnupg/gpg.conf -> /Users/dipamvasani/dotfiles/gpg.conf
Link exists ~/.ipython/profile_default/ipython_config.py -> /Users/dipamvasani/dotfiles/ipython/ipython_config.py
~/.gitconfig already exists but is a regular file or directory
Link exists ~/.local/share/jupyter/nbextensions -> /Users/dipamvasani/dotfiles/jupyter/nbextensions
Link exists ~/.ipython/profile_default/ipython_kernel_config.py -> /Users/dipamvasani/dotfiles/ipython/ipython_kernel_config.py
Link exists ~/.aria2/aria2.conf -> /Users/dipamvasani/dotfiles/aria2.conf
Link exists ~/.irssi -> /Users/dipamvasani/dotfiles/irssi
Link exists ~/.hgrc -> /Users/dipamvasani/dotfiles/hgrc
Link exists ~/.shell -> /Users/dipamvasani/dotfiles/shell
~/.zsh already exists but is a regular file or directory
~/.vim already exists but is a regular file or directory
Link exists ~/.emacs.d -> /Users/dipamvasani/dotfiles/emacs.d
Link exists ~/.pythonrc -> /Users/dipamvasani/dotfiles/pythonrc
Link exists ~/.rtorrent.rc -> /Users/dipamvasani/dotfiles/rtorrent.rc
Link exists ~/.screenrc -> /Users/dipamvasani/dotfiles/screenrc
Link exists ~/.inputrc -> /Users/dipamvasani/dotfiles/inputrc
~/.vimrc already exists but is a regular file or directory
Link exists ~/.agignore -> /Users/dipamvasani/dotfiles/agignore
Link exists ~/.jupyter/jupyter_notebook_config.py -> /Users/dipamvasani/dotfiles/jupyter/jupyter_notebook_config.py
Link exists ~/.zshrc -> /Users/dipamvasani/dotfiles/zshrc
Link exists ~/.tmux.conf -> /Users/dipamvasani/dotfiles/tmux.conf
Link exists ~/.ipython/profile_default/startup/disable_warnings.py -> /Users/dipamvasani/dotfiles/ipython/disable_warnings.py
~/.jupyter/nbconfig/notebook.json already exists but is a regular file or directory
Link exists ~/.emacs -> /Users/dipamvasani/dotfiles/emacs
Link exists ~/.gitignore_global -> /Users/dipamvasani/dotfiles/gitignore_global
Link exists ~/.axelrc -> /Users/dipamvasani/dotfiles/axelrc
Link exists ~/.haskeline -> /Users/dipamvasani/dotfiles/haskeline
~/.bash_profile already exists but is a regular file or directory
~/.bashrc already exists but is a regular file or directory
Some links were not successfully set up
Path exists /Users/dipamvasani/.rtorrent/session
Path exists /Users/dipamvasani/.rtorrent/watch
Path exists /Users/dipamvasani/.rtorrent/downloads
All paths have been set up
git submodule sync --recursive
git update-submodules
Command [git update-submodules] failed
git cleanall -f emacs.d/vendor/ irssi/scripts/vendor/ jupyter/nbextensions/ shell/plugins/ vim/pack/vendor/start/ zsh/plugins/

Command [git cleanall -f emacs.d/vendor/ irssi/scripts/vendor/ jupyter/nbextensions/ shell/plugins/ vim/pack/vendor/start/ zsh/plugins/
] failed
Some commands were not successfully executed

==> Some tasks were not executed successfully
```

How do I solve it and how do I setup zsh, oh-my-zsh and all the plugins that you are using? I am new to all this so forgive the simple doubt

**Comment by deepword18** [comment]
FYI, I already had zsh installed but I really liked your shell from the missing semester course and so found your dotfiles

**Comment by anishathalye** [comment]
Some links aren't being created because regular files exist in their place already (e.g. `~/.bashrc` is a regular file, and I've set up my dotfiles to not forcibly replace that regular file with a symlink). If you back up and then delete those regular files, and re-run `./install`, it should work. If you want to understand more about what's going on when you `./install`, see the documentation for [Dotbot](https://github.com/anishathalye/dotbot).

I'm not using oh-my-zsh, just [a few plugins](https://github.com/anishathalye/dotfiles/tree/master/zsh/plugins), zsh-syntax-highlighting and zsh-completions. My zsh theme is mostly contained in this dotfiles repo, but it cooperates with a color scheme that's in my dotfiles-local repo (e.g. for iTerm2, I use this [color scheme](https://github.com/anishathalye/dotfiles-local/tree/mac/iTerm2)).

By the way, as I've written in more detail [here](https://www.anishathalye.com/2014/08/03/managing-your-dotfiles/), I recommend reading/understanding and then borrowing _parts_ of others' dotfiles, rather than forking them / using them in their entirety. Along those lines, my dotfiles that are publicly available on GitHub are meant more as a reference for other people who are curious about how certain parts work, and I'm not necessarily trying to make them usable as-is by others.

**Comment by deepword18** [comment]
Thank you for the detailed explanation. This helps a lot :)
