### ISSUE TITLE
Docker - segmentation fault

### ISSUE THREAD

**Issue by dhilsand** [anishathalye/dotfiles#2]
I was testing these dotfiles in a docker container before I install it on my computer. It gives me a segmentation fault as soon as I start zsh.

Here's what I did: 
`docker run -it ubuntu:latest /bin/bash`
Inside the docker container
`sudo apt-get install git python vim zsh`
I cloned your repo, ran the ./install script and tried executing /bin/zsh.
Immediately gives a segmentation fault.

Also the ./install script couldn't finish, I got:

```
Command [git update-submodules] failed
Some commands were not successfully executed
```

**Comment by anishathalye** [comment]
Yeah, it's an issue with old versions of zsh. Works fine on 5.0.8, for example.

I spent an hour looking into this a while ago, and this was the result: https://github.com/anishathalye/dotfiles/commit/1ef3d791c25f9f5d67ce66f1b7b9782554c84146 (reverted since it was kinda annoying). There's some more details in the commit message, which may help if you want to investigate.

So you could use the workaround that I used in that commit, or just update to the latest version of zsh.
