### ISSUE TITLE
Command [git update-submodules] failed

### ISSUE THREAD

**Issue by wenjie-lu** [anishathalye/dotfiles#6]
After git clone and run install, I ran into the error message: 

git submodule sync --recursive
git update-submodules
Command [git update-submodules] failed
git cleanall -f emacs.d/vendor/ irssi/scripts/vendor/ jupyter/nbextensions/ shell/plugins/ vim/bundle/ zsh/plugins/

I'm running this on a freshly installed mac.

**Comment by anishathalye** [comment]
You can see the error by running `git update-submodules` on its own. I think this happened because https://github.com/emacsmirror/undo-tree, a submodule this repo depends on, was force pushed. This is fixed in b1f82c91a9244c7dfda9e04f17f493eff43b606b (by removing undo-tree, which I didn't really use much anyways; I think I remember this force-push thing happening before with that repo, and it's kind of inconvenient). So if you `git pull` and then `./install`, it should probably work.

(By the way, my dotfiles are not necessarily designed for reuse as-is by others; in fact, I don't [recommend](https://www.anishathalye.com/2014/08/03/managing-your-dotfiles/) this mode of use. It might be better to start with a clean repo, and take pieces of other people's code/configuration after reading and understanding them.)
