### ISSUE TITLE
Is there a way to make aliases work with the xin function ?

### ISSUE THREAD

**Issue by danielfalbo** [anishathalye/dotfiles#8]
https://github.com/anishathalye/dotfiles/blob/b4ef16a1c91948d9f247175b1219c02887844a7c/shell/aliases.sh#L85

Amazing dotfiles by the way :)

**Comment by anishathalye** [comment]
I am not sure how to do this. Using `eval` (`eval "${@}")` invokes alias expansion but breaks arguments that have spaces in them. Maybe some clever use of eval will work.

This is somewhat tricky because Zsh performs alias expansion pretty early on, before parameter expansion: http://zsh.sourceforge.net/Doc/Release/Expansion.html

**Comment by danielfalbo** [comment]
Thank you! This is actually perfect for all my scenarios :) Should I close the issue ?

**Comment by anishathalye** [comment]
Nice, glad it solves the problem for you :)

Just be aware that, for example, `xin .. echo one "two three"` will call `echo` with argv[1] = "one", argv[2] = "two", argv[3] = "three", whereas without the eval, it'll call echo with argv[1] = "one" and argv[2] = "two three". This might break some use cases (e.g. quoted file names with spaces inside).
